### ISSUE TITLE
Link to Readme.md Template wrong

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/id#13]
In Readme.md of id there is the information:

create a README following the template in https://github.com/sebbader/id/template/README.md

The link is invalid it seems, please update with new link

Thanks, Birgit

**Comment by sebbader** [comment]
Hello Birgit,

can you please see if this PR solves the issue.

**Comment by BirgitBoss** [comment]
Thanks for fixing! I commented in the PR itself

**Comment by sebbader** [comment]
The PR has been accepted, so closing the issue.
