### ISSUE TITLE
Repository Description is missing 

### ISSUE THREAD

**Issue by egekorkan** [admin-shell-io/id#20]
When looking at all the repositories of the IDTA, this one looks odd since it lacks a description (it is also recommended by GitHub at https://github.com/admin-shell-io/id/community). A one sentence description would be nice. Below is my proposal, largely inspired by the readme.

> A collection of IDTA-managed Asset Administration Shell Identifiers and registration process

![image](https://user-images.githubusercontent.com/20195407/155757993-2775a259-f047-4f36-942b-2d1a06133ee2.png)

This repository seems to be not active anymore with a bunch of simple and not merged PRs but I wanted to open the issue anyway.

**Comment by sebbader** [comment]
Hi @egekorkan, thanks for the suggestions, I added your proposal and extended it a bit.

**Comment by sebbader** [comment]
> This repository seems to be not active anymore

Actually it is, at least the namespace is used actively by the IDTA working groups. I just needed to find free time to do the homework in the repo :-).

**Comment by sebbader** [comment]
Let me know if that fulfils your comment. If so, I'll close the issue in a few days.

**Comment by egekorkan** [comment]
Thanks @sebbader ! It looks good now, closing.
